slice_name: Country of Citizenship
description: null
certified_by: null
certification_details: null
viz_type: world_map
params:
  adhoc_filters: []
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  country_fieldtype: name
  datasource: 42__table
  entity: country_citizen
  granularity_sqla: time_start
  linear_color_scheme: preset_div_1
  max_bubble_size: '25'
  metric: count
  queryFields:
    entity: groupby
    metric: metrics
    secondary_metric: metrics
  row_limit: null
  secondary_metric:
    aggregate: COUNT
    column:
      column_name: country_live
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1570
      is_dttm: false
      python_date_format: null
      type: TEXT
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT(country_live)
    optionName: metric_azxwoyei39f_d7xgzshjnw6
    sqlExpression: null
  show_bubbles: true
  slice_id: 1388
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: world_map
  annotation_layers: []
cache_timeout: null
uuid: db2ecafe-e954-499a-9015-bac7390bf61a
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
