slice_name: Country Growth Rate
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 1__table
  viz_type: echarts_timeseries_line
  slice_id: 75
  x_axis: year
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - sum__SP_POP_TOTL
  groupby:
  - country_name
  adhoc_filters:
  - clause: WHERE
    subject: year
    operator: TEMPORAL_RANGE
    comparator: '1960-01-01 : 2014-01-02'
    expressionType: SIMPLE
  limit: '25'
  order_desc: true
  row_limit: 5000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipSortByMetric: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"year","op":"TEMPORAL_RANGE","val":"1960-01-01
  : 2014-01-02"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"year","label":"year","expressionType":"SQL"},"country_name"],"metrics":["sum__SP_POP_TOTL"],"orderby":[["sum__SP_POP_TOTL",false]],"annotation_layers":[],"row_limit":5000,"series_columns":["country_name"],"series_limit":25,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["year"],"columns":["country_name"],"aggregates":{"sum__SP_POP_TOTL":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rename","options":{"columns":{"sum__SP_POP_TOTL":null},"level":0,"inplace":true}},{"operation":"flatten"}]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"1960-01-01
  : 2014-01-02","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"year"}],"annotation_layers":[],"color_scheme":"supersetColors","comparison_type":"values","dashboards":[],"datasource":"1__table","extra_form_data":{},"forecastInterval":0.8,"forecastPeriods":10,"groupby":["country_name"],"legendOrientation":"top","legendType":"scroll","limit":"25","markerSize":6,"metrics":["sum__SP_POP_TOTL"],"only_total":true,"opacity":0.2,"order_desc":true,"rich_tooltip":true,"row_limit":5000,"seriesType":"line","show_empty_columns":true,"show_legend":true,"slice_id":111,"sort_series_type":"sum","tooltipSortByMetric":false,"tooltipTimeFormat":"smart_date","truncate_metric":true,"viz_type":"echarts_timeseries_line","x_axis":"year","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"x_axis_time_format":"smart_date","x_axis_title_margin":15,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_title_margin":15,"y_axis_title_position":"Left","zoomable":true,"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 5cee9cff-f5d3-4e44-8889-0d13cd954d0b
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
