slice_name: 'Current Developers: Is this your first development job?'
viz_type: big_number_total
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Currently A Developer
    expressionType: SIMPLE
    filterOptionName: filter_fvi0jg9aii_2lekqrhy7qk
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: developer_type
  datasource: 42__table
  granularity_sqla: time_start
  header_font_size: 0.4
  metric:
    aggregate: COUNT
    column:
      column_name: is_software_dev
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1463
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT(is_software_dev)
    optionName: metric_9i1kctig9yr_sizo6ihd2o
    sqlExpression: null
  queryFields:
    metric: metrics
  slice_id: 1361
  subheader_font_size: 0.15
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: bfe5a8e6-146f-ef59-5e6c-13d519b236a8
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
