slice_name: Degrees vs Income
description: null
certified_by: null
certification_details: null
viz_type: box_plot
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '1'
    expressionType: SIMPLE
    filterOptionName: filter_s1jzmdwgeg_p3er4w56uy
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: is_software_dev
  - clause: WHERE
    comparator: '200000'
    expressionType: SIMPLE
    filterOptionName: filter_ojzq4njnuog_zj0dux944z
    isExtra: false
    isNew: false
    operator: <=
    sqlExpression: null
    subject: last_yr_income
  color_scheme: supersetColors
  columns: []
  datasource: 42__table
  granularity_sqla: time_start
  groupby:
  - school_degree
  metrics:
  - aggregate: SUM
    column:
      column_name: last_yr_income
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1589
      is_dttm: false
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(last_yr_income)
    optionName: metric_bgqj8nnvz8k_07w8bbh1bc6q
    sqlExpression: null
  number_format: SMART_NUMBER
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  slice_id: 1376
  time_grain_sqla: null
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: box_plot
  whiskerOptions: Tukey
  x_ticks_layout: "45\xB0"
  annotation_layers: []
query_context: "{\"datasource\":{\"id\":19,\"type\":\"table\"},\"force\":false,\"\
  queries\":[{\"time_range\":\"No filter\",\"granularity\":\"time_start\",\"filters\"\
  :[{\"col\":\"is_software_dev\",\"op\":\"==\",\"val\":\"1\"},{\"col\":\"last_yr_income\"\
  ,\"op\":\"<=\",\"val\":\"200000\"}],\"extras\":{\"time_grain_sqla\":null,\"having\"\
  :\"\",\"where\":\"\"},\"applied_time_extras\":{},\"columns\":[\"time_start\",\"\
  school_degree\"],\"metrics\":[{\"aggregate\":\"SUM\",\"column\":{\"column_name\"\
  :\"last_yr_income\",\"description\":null,\"expression\":null,\"filterable\":true,\"\
  groupby\":true,\"id\":1589,\"is_dttm\":false,\"python_date_format\":null,\"type\"\
  :\"DOUBLE PRECISION\",\"verbose_name\":null},\"expressionType\":\"SIMPLE\",\"hasCustomLabel\"\
  :false,\"isNew\":false,\"label\":\"SUM(last_yr_income)\",\"optionName\":\"metric_bgqj8nnvz8k_07w8bbh1bc6q\"\
  ,\"sqlExpression\":null}],\"annotation_layers\":[],\"series_columns\":[\"school_degree\"\
  ],\"series_limit\":0,\"order_desc\":true,\"url_params\":{},\"custom_params\":{},\"\
  custom_form_data\":{},\"post_processing\":[{\"operation\":\"boxplot\",\"options\"\
  :{\"whisker_type\":\"tukey\",\"groupby\":[\"school_degree\"],\"metrics\":[\"SUM(last_yr_income)\"\
  ]}}]}],\"form_data\":{\"adhoc_filters\":[{\"clause\":\"WHERE\",\"comparator\":\"\
  1\",\"expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_s1jzmdwgeg_p3er4w56uy\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"==\",\"sqlExpression\":null,\"\
  subject\":\"is_software_dev\"},{\"clause\":\"WHERE\",\"comparator\":\"200000\",\"\
  expressionType\":\"SIMPLE\",\"filterOptionName\":\"filter_ojzq4njnuog_zj0dux944z\"\
  ,\"isExtra\":false,\"isNew\":false,\"operator\":\"<=\",\"sqlExpression\":null,\"\
  subject\":\"last_yr_income\"}],\"annotation_layers\":[],\"color_scheme\":\"supersetColors\"\
  ,\"columns\":[],\"datasource\":\"19__table\",\"granularity_sqla\":\"time_start\"\
  ,\"groupby\":[\"school_degree\"],\"metrics\":[{\"aggregate\":\"SUM\",\"column\"\
  :{\"column_name\":\"last_yr_income\",\"description\":null,\"expression\":null,\"\
  filterable\":true,\"groupby\":true,\"id\":1589,\"is_dttm\":false,\"python_date_format\"\
  :null,\"type\":\"DOUBLE PRECISION\",\"verbose_name\":null},\"expressionType\":\"\
  SIMPLE\",\"hasCustomLabel\":false,\"isNew\":false,\"label\":\"SUM(last_yr_income)\"\
  ,\"optionName\":\"metric_bgqj8nnvz8k_07w8bbh1bc6q\",\"sqlExpression\":null}],\"\
  number_format\":\"SMART_NUMBER\",\"queryFields\":{\"columns\":\"groupby\",\"groupby\"\
  :\"groupby\",\"metrics\":\"metrics\"},\"slice_id\":138,\"time_grain_sqla\":null,\"\
  time_range\":\"No filter\",\"time_range_endpoints\":[\"inclusive\",\"exclusive\"\
  ],\"url_params\":{},\"viz_type\":\"box_plot\",\"whiskerOptions\":\"Tukey\",\"x_ticks_layout\"\
  :\"45\xB0\",\"force\":false,\"result_format\":\"json\",\"result_type\":\"full\"\
  },\"result_format\":\"json\",\"result_type\":\"full\"}"
cache_timeout: null
uuid: 617fae11-aaf7-475b-aa2a-3b08b8f2f6a6
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
