slice_name: First Time Developer?
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Currently A Developer
    expressionType: SIMPLE
    filterOptionName: filter_fvi0jg9aii_2lekqrhy7qk
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: developer_type
  color_scheme: supersetColors
  datasource: 42__table
  donut: true
  granularity_sqla: time_start
  groupby:
  - first_time_developer
  innerRadius: 43
  labels_outside: true
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 69
  label_type: key
  queryFields:
    groupby: groupby
    metric: metrics
  row_limit: null
  show_labels: true
  show_legend: false
  slice_id: 3632
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: pie
  annotation_layers: []
query_context: '{"datasource":{"id":19,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"time_start","filters":[{"col":"developer_type","op":"==","val":"Currently
  A Developer"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["first_time_developer"],"metrics":["count"],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"Currently
  A Developer","expressionType":"SIMPLE","filterOptionName":"filter_fvi0jg9aii_2lekqrhy7qk","isExtra":false,"isNew":false,"operator":"==","sqlExpression":null,"subject":"developer_type"}],"annotation_layers":[],"color_scheme":"supersetColors","datasource":"19__table","donut":true,"granularity_sqla":"time_start","groupby":["first_time_developer"],"innerRadius":43,"label_type":"key","labels_outside":true,"metric":"count","number_format":"SMART_NUMBER","outerRadius":69,"queryFields":{"groupby":"groupby","metric":"metrics"},"row_limit":null,"show_labels":true,"show_legend":false,"slice_id":137,"time_range":"No
  filter","time_range_endpoints":["inclusive","exclusive"],"url_params":{},"viz_type":"pie","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 156affb9-b30f-43a3-ab3d-92ffc528e2eb
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
