slice_name: Games
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns:
  - name
  - global_sales
  - platform
  - genre
  - publisher
  - year
  color_pn: false
  datasource: 21__table
  granularity_sqla: year
  groupby:
  - name
  include_search: true
  metrics:
  - aggregate: SUM
    column:
      column_name: global_sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 887
      is_dttm: false
      optionName: _col_Global_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(Global_Sales)
    optionName: metric_pkpvgdsf70d_pnqv77v0x2p
    sqlExpression: null
  order_by_cols:
  - '["global_sales", false]'
  order_desc: true
  page_length: '15'
  percent_metrics: []
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: raw
  row_limit: null
  show_cell_bars: false
  slice_id: 1394
  table_filter: false
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: table
  annotation_layers: []
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"year","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["name","global_sales","platform","genre","publisher","year"],"orderby":[["global_sales",false]],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"adhoc_filters":[],"all_columns":["name","global_sales","platform","genre","publisher","year"],"annotation_layers":[],"color_pn":false,"datasource":"2__table","granularity_sqla":"year","groupby":["name"],"include_search":true,"metrics":[{"aggregate":"SUM","column":{"column_name":"global_sales","description":null,"expression":null,"filterable":true,"groupby":true,"id":887,"is_dttm":false,"optionName":"_col_Global_Sales","python_date_format":null,"type":"DOUBLE
  PRECISION","verbose_name":null},"expressionType":"SIMPLE","hasCustomLabel":false,"isNew":false,"label":"SUM(Global_Sales)","optionName":"metric_pkpvgdsf70d_pnqv77v0x2p","sqlExpression":null}],"order_by_cols":["[\"global_sales\",
  false]"],"order_desc":true,"page_length":"15","percent_metrics":[],"queryFields":{"groupby":"groupby","metrics":"metrics"},"query_mode":"raw","row_limit":null,"show_cell_bars":false,"slice_id":103,"table_filter":false,"table_timestamp_format":"smart_date","time_grain_sqla":"P1D","time_range":"No
  filter","time_range_endpoints":["inclusive","exclusive"],"url_params":{},"viz_type":"table","force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 7b79d4b1-0f1a-464f-9e96-b34617bba92c
version: 1.0.0
dataset_uuid: 53d47c0c-c03d-47f0-b9ac-81225f808283
