slice_name: Games per Genre over time
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 2__table
  viz_type: echarts_timeseries_line
  slice_id: 80
  x_axis: year
  time_grain_sqla: null
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - count
  groupby:
  - genre
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: year
  order_desc: true
  row_limit: null
  truncate_metric: true
  show_empty_columns: true
  rolling_type: null
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title: Year Published
  x_axis_title_margin: 30
  y_axis_title: '# of Games Published'
  y_axis_title_margin: 50
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  only_total: true
  opacity: 0.2
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
cache_timeout: null
uuid: 915fca33-c2b6-4f8e-afdd-d5061b03d35d
version: 1.0.0
dataset_uuid: 53d47c0c-c03d-47f0-b9ac-81225f808283
