slice_name: Gender
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 42__table
  donut: true
  granularity_sqla: time_start
  groupby:
  - gender
  innerRadius: 44
  label_line: true
  labels_outside: true
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 69
  label_type: key
  queryFields:
    groupby: groupby
    metric: metrics
  row_limit: 10000
  show_labels: true
  show_legend: false
  slice_id: 1385
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: pie
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 215f8a20-6fc5-47a8-aa58-01cd3ce52692
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
