slice_name: Highest degree held
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: '0'
    expressionType: SIMPLE
    filterOptionName: filter_qzz67uip1ue_jw3rr6tzo3a
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: is_software_dev
  all_columns: []
  color_pn: true
  datasource: 42__table
  granularity_sqla: time_start
  groupby:
  - school_degree
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  percent_metrics:
  - aggregate: COUNT
    column:
      column_name: school_degree
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1574
      is_dttm: false
      python_date_format: null
      type: TEXT
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: COUNT(school_degree)
    optionName: metric_vsilrouxw3q_iactbbmvdv
    sqlExpression: null
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: aggregate
  row_limit: null
  show_cell_bars: true
  slice_id: 1369
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: table
cache_timeout: null
uuid: 9f7d2b9c-6b3a-69f9-f03e-d3a141514639
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
