slice_name: Last Year Income Distribution
description: null
certified_by: null
certification_details: null
viz_type: histogram
params:
  adhoc_filters:
  - clause: WHERE
    comparator: Currently A Developer
    expressionType: SIMPLE
    filterOptionName: filter_fvi0jg9aii_2lekqrhy7qk
    isExtra: false
    isNew: false
    operator: ==
    sqlExpression: null
    subject: developer_type
  - clause: WHERE
    comparator: '100000'
    expressionType: SIMPLE
    filterOptionName: filter_khdc3iypzjg_3g6h02b4f2p
    isExtra: false
    isNew: false
    operator: <=
    sqlExpression: null
    subject: last_yr_income
  all_columns_x:
  - last_yr_income
  color_scheme: supersetColors
  datasource: 42__table
  granularity_sqla: time_start
  groupby: []
  label_colors: {}
  link_length: '10'
  queryFields:
    groupby: groupby
  row_limit: null
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: histogram
  annotation_layers: []
query_context: null
cache_timeout: null
uuid: 2fe774e8-3815-46eb-9725-cefcd56f1789
version: 1.0.0
dataset_uuid: d95a2865-53ce-1f82-a53d-8e3c89331469
