slice_name: Life Expectancy VS Rural %
description: null
certified_by: null
certification_details: null
viz_type: bubble_v2
params:
  adhoc_filters:
  - clause: WHERE
    comparator:
    - TCA
    - MNP
    - DMA
    - MHL
    - MCO
    - SXM
    - CYM
    - TUV
    - IMY
    - KNA
    - ASM
    - ADO
    - AMA
    - PLW
    expressionType: SIMPLE
    filterOptionName: 2745eae5
    operator: NOT IN
    subject: country_code
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_name
  granularity_sqla: year
  groupby: []
  limit: 0
  markup_type: markdown
  max_bubble_size: '50'
  row_limit: 5000
  series: region
  show_bubbles: true
  since: '2011-01-01'
  size: sum__SP_POP_TOTL
  time_range: '2014-01-01 : 2014-01-02'
  time_range_endpoints:
  - inclusive
  - exclusive
  until: '2011-01-02'
  viz_type: bubble
  x: sum__SP_RUR_TOTL_ZS
  y: sum__SP_DYN_LE00_IN
  annotation_layers: []
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"time_range":"2011-01-01
  : 2011-01-02","granularity":"year","filters":[{"col":"country_code","op":"NOT IN","val":["TCA","MNP","DMA","MHL","MCO","SXM","CYM","TUV","IMY","KNA","ASM","ADO","AMA","PLW"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["country_name","region"],"metrics":["sum__SP_POP_TOTL","sum__SP_RUR_TOTL_ZS","sum__SP_DYN_LE00_IN"],"annotation_layers":[],"row_limit":5000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":["TCA","MNP","DMA","MHL","MCO","SXM","CYM","TUV","IMY","KNA","ASM","ADO","AMA","PLW"],"expressionType":"SIMPLE","filterOptionName":"2745eae5","operator":"NOT
  IN","subject":"country_code"}],"annotation_layers":[],"compare_lag":"10","compare_suffix":"o10Y","country_fieldtype":"cca3","datasource":"1__table","entity":"country_name","granularity_sqla":"year","groupby":[],"limit":0,"markup_type":"markdown","max_bubble_size":"50","row_limit":5000,"series":"region","show_bubbles":true,"size":"sum__SP_POP_TOTL","slice_id":110,"time_range":"2011-01-01
  : 2011-01-02","time_range_endpoints":["inclusive","exclusive"],"viz_type":"bubble_v2","x":"sum__SP_RUR_TOTL_ZS","y":"sum__SP_DYN_LE00_IN","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 288053f4-91ed-4bcc-a8ff-5943ed9a145c
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
