slice_name: Members per Channel
description: null
certified_by: null
certification_details: null
viz_type: treemap_v2
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 57__table
  groupby:
  - channel_name
  label_colors: {}
  metric: count
  number_format: SMART_NUMBER
  queryFields:
    groupby: groupby
    metrics: metrics
  row_limit: null
  slice_id: 2396
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  treemap_ratio: 1.618033988749895
  url_params: {}
  viz_type: treemap_v2
  annotation_layers: []
cache_timeout: null
uuid: 0161513a-79d4-4dc6-94f7-5c6cbf9e5cff
version: 1.0.0
dataset_uuid: 3d9c0054-b31b-4102-92de-b1ef9f9e5e77
