slice_name: Number of Deals (for each Combination)
description: null
certified_by: null
certification_details: null
viz_type: heatmap
params:
  adhoc_filters: []
  all_columns_x: deal_size
  all_columns_y: product_line
  bottom_margin: 100
  canvas_image_rendering: pixelated
  datasource: 23__table
  granularity_sqla: order_date
  left_margin: 75
  linear_color_scheme: schemePuBuGn
  metric: count
  normalize_across: heatmap
  normalized: true
  queryFields:
    metric: metrics
  row_limit: null
  show_legend: true
  show_perc: true
  show_values: true
  slice_id: 2810
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: heatmap
  xscale_interval: null
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  yscale_interval: null
  annotation_layers: []
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"order_date","filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count"],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"adhoc_filters":[],"all_columns_x":"deal_size","all_columns_y":"product_line","annotation_layers":[],"bottom_margin":100,"canvas_image_rendering":"pixelated","datasource":"3__table","granularity_sqla":"order_date","left_margin":75,"linear_color_scheme":"schemePuBuGn","metric":"count","normalize_across":"heatmap","normalized":true,"queryFields":{"metric":"metrics"},"row_limit":null,"show_legend":true,"show_perc":true,"show_values":true,"slice_id":92,"sort_x_axis":"alpha_asc","sort_y_axis":"alpha_asc","time_range":"No
  filter","time_range_endpoints":["inclusive","exclusive"],"url_params":{},"viz_type":"heatmap","xscale_interval":null,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","yscale_interval":null,"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 61ca81cb-db24-4f8d-8ccc-a2430db75131
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
