slice_name: Overall Sales (By Product Line)
description: null
certified_by: null
certification_details: null
viz_type: pie
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 23__table
  donut: true
  granularity_sqla: order_date
  groupby:
  - product_line
  innerRadius: 41
  label_line: true
  labels_outside: true
  metric:
    aggregate: SUM
    column:
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 917
      is_dttm: false
      optionName: _col_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: (Sales)
    optionName: metric_3sk6pfj3m7i_64h77bs4sly
    sqlExpression: null
  number_format: SMART_NUMBER
  outerRadius: 65
  label_type: key
  queryFields:
    groupby: groupby
    metric: metrics
  row_limit: null
  show_labels: true
  show_labels_threshold: 2
  show_legend: false
  slice_id: 670
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: pie
  annotation_layers: []
cache_timeout: null
uuid: 46914afc-f057-441e-bcc6-d02f91921fd9
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
