slice_name: Rural Breakdown
description: null
certified_by: null
certification_details: null
viz_type: sunburst_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  columns:
  - region
  - country_name
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 5000
  secondary_metric:
    aggregate: SUM
    column:
      column_name: SP_RUR_TOTL
      optionName: _col_SP_RUR_TOTL
      type: DOUBLE
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rural Population
  show_bubbles: true
  since: '2011-01-01'
  time_range_endpoints:
  - inclusive
  - exclusive
  until: '2011-01-02'
  viz_type: sunburst_v2
  annotation_layers: []
  adhoc_filters:
  - clause: WHERE
    subject: year
    operator: TEMPORAL_RANGE
    comparator: '2014-01-01 : 2014-01-02'
    expressionType: SIMPLE
cache_timeout: null
uuid: 0bd51d81-79ce-4f66-97fe-306451675239
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
