slice_name: '% Rural'
description: null
certified_by: null
certification_details: null
viz_type: world_map
params:
  datasource: 1__table
  viz_type: world_map
  slice_id: 108
  entity: country_code
  country_fieldtype: cca3
  metric: sum__SP_RUR_TOTL_ZS
  adhoc_filters:
  - clause: WHERE
    subject: year
    operator: TEMPORAL_RANGE
    comparator: '2014-01-01 : 2014-01-02'
    expressionType: SIMPLE
  row_limit: 5000
  show_bubbles: true
  secondary_metric:
    aggregate: SUM
    column:
      column_name: SP_RUR_TOTL
      optionName: _col_SP_RUR_TOTL
      type: DOUBLE
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Rural Population
  max_bubble_size: '25'
  color_picker:
    r: 4
    g: 55
    b: 224
    a: 1
  color_by: metric
  linear_color_scheme: superset_seq_1
  color_scheme: supersetAndPresetColors
  y_axis_format: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 11
cache_timeout: null
uuid: bb584143-8731-4331-b674-aa23f2c06da0
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
