slice_name: Screen grid
description: null
certified_by: null
certification_details: null
viz_type: deck_screengrid
params:
  color_picker:
    a: 1
    b: 0
    g: 255
    r: 14
  datasource: 5__table
  granularity_sqla: null
  grid_size: 20
  groupby: []
  mapbox_style: mapbox://styles/mapbox/dark-v9
  point_radius: Auto
  point_radius_fixed:
    type: fix
    value: 2000
  point_unit: square_m
  row_limit: 5000
  size: count
  spatial:
    latCol: LAT
    lonCol: LON
    type: latlong
  time_grain_sqla: null
  time_range: No filter
  viewport:
    bearing: -4.952916738791771
    latitude: 37.76024135844065
    longitude: -122.41827069521386
    pitch: 4.750411100577438
    zoom: 14.161641703941438
  viz_type: deck_screengrid
cache_timeout: null
uuid: 25c0c0c3-865d-4178-8a90-90127544cdd6
version: 1.0.0
dataset_uuid: c4ae2fd1-21b5-46d7-b572-337cf84bc785
