slice_name: 'Top 10 Games: Proportion of Sales in Markets'
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 2__table
  viz_type: echarts_timeseries_bar
  slice_id: 23
  x_axis: name
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: SUM
    column:
      column_name: na_sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 883
      is_dttm: false
      optionName: _col_NA_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: North America
    optionName: metric_a943v7wg5g_0mm03hrsmpf
    sqlExpression: null
  - aggregate: SUM
    column:
      column_name: eu_sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 884
      is_dttm: false
      optionName: _col_EU_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Europe
    optionName: metric_bibau54x0rb_dwrjtqkbyso
    sqlExpression: null
  - aggregate: SUM
    column:
      column_name: jp_sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 885
      is_dttm: false
      optionName: _col_JP_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Japan
    optionName: metric_06whpr2oyhw_4l88xxu6zvd
    sqlExpression: null
  - aggregate: SUM
    column:
      column_name: other_sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 886
      is_dttm: false
      optionName: _col_Other_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Other
    optionName: metric_pcx05ioxums_ibr16zvi74
    sqlExpression: null
  groupby: []
  contributionMode: row
  adhoc_filters:
  - clause: WHERE
    comparator: '10'
    expressionType: SIMPLE
    filterOptionName: filter_juemdnqji5_d6fm8tuf4rc
    isExtra: false
    isNew: false
    operator: <=
    sqlExpression: null
    subject: rank
  - clause: WHERE
    subject: year
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_desc: true
  row_limit: null
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  stack: Stack
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelRotation: 45
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
cache_timeout: null
uuid: f770a369-8dfe-4133-8ecc-559c0db5703d
version: 1.0.0
dataset_uuid: 53d47c0c-c03d-47f0-b9ac-81225f808283
