slice_name: Top Timezones
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  align_pn: false
  all_columns: []
  color_pn: true
  datasource: 31__table
  granularity_sqla: updated
  groupby:
  - tz
  include_search: false
  metrics:
  - count
  order_by_cols: []
  order_desc: true
  page_length: 0
  percent_metrics: []
  queryFields:
    groupby: groupby
    metrics: metrics
  query_mode: aggregate
  row_limit: 10
  show_cell_bars: true
  slice_id: 1908
  table_timestamp_format: smart_date
  time_grain_sqla: P1D
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: table
  annotation_layers: []
query_context: '{"datasource":{"id":5,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"updated","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["tz"],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"adhoc_filters":[],"align_pn":false,"all_columns":[],"annotation_layers":[],"color_pn":true,"datasource":"5__table","granularity_sqla":"updated","groupby":["tz"],"include_search":false,"metrics":["count"],"order_by_cols":[],"order_desc":true,"page_length":0,"percent_metrics":[],"queryFields":{"groupby":"groupby","metrics":"metrics"},"query_mode":"aggregate","row_limit":10,"show_cell_bars":true,"slice_id":115,"table_timestamp_format":"smart_date","time_grain_sqla":"P1D","time_range":"No
  filter","time_range_endpoints":["inclusive","exclusive"],"url_params":{},"viz_type":"table","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a96a2be6-1a3f-415e-9f8f-e36192f2e824
version: 1.0.0
dataset_uuid: 7195db6b-2d17-7619-b7c7-26b15378df8c
