slice_name: Total Revenue
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 3__table
  viz_type: big_number
  slice_id: 83
  x_axis: order_date
  metric:
    aggregate: SUM
    column:
      column_name: sales
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 917
      is_dttm: false
      optionName: _col_Sales
      python_date_format: null
      type: DOUBLE PRECISION
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: (Sales)
    optionName: metric_twq59hf4ej_g70qjfmehsq
    sqlExpression: null
  adhoc_filters:
  - clause: WHERE
    subject: order_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  show_trend_line: true
  start_y_axis_at_zero: true
  color_picker:
    r: 0
    g: 148
    b: 255
    a: 1
  header_font_size: 0.4
  subheader_font_size: 0.3
  y_axis_format: $,.2f
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 9
  - 8
cache_timeout: null
uuid: 75d88d4c-993b-4db1-917d-f1a6114200c5
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
