slice_name: Total Items Sold
viz_type: big_number_total
params:
  adhoc_filters: []
  datasource: 23__table
  granularity_sqla: order_date
  header_font_size: 0.4
  metric:
    aggregate: SUM
    column:
      column_name: quantity_ordered
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 914
      is_dttm: false
      python_date_format: null
      type: BIGINT
      verbose_name: null
    expressionType: SIMPLE
    hasCustomLabel: false
    isNew: false
    label: SUM(Sales)
    optionName: metric_twq59hf4ej_g70qjfmehsq
    sqlExpression: null
  queryFields:
    metric: metrics
  subheader: ''
  subheader_font_size: 0.15
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: c3d643cd-fd6f-4659-a5b7-59402487a8d0
version: 1.0.0
dataset_uuid: e8623bb9-5e00-f531-506a-19607f5f8005
