slice_name: Vaccine Candidates per Country & Stage
description: null
certified_by: null
certification_details: null
viz_type: sunburst_v2
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 69__table
  columns:
  - product_category
  - clinical_stage
  linear_color_scheme: schemeYlOrBr
  metric: count
  queryFields:
    groupby: groupby
    metric: metrics
    secondary_metric: metrics
  row_limit: 10000
  slice_id: 3964
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: sunburst_v2
  annotation_layers: []
cache_timeout: null
uuid: 6cae1766-ef85-450b-925d-e8f8c79f9b80
version: 1.0.0
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
