slice_name: Vaccine Candidates per Country & Stage
viz_type: heatmap
params:
  adhoc_filters: []
  all_columns_x: clinical_stage
  all_columns_y: country_name
  bottom_margin: auto
  canvas_image_rendering: pixelated
  datasource: 14__table
  left_margin: auto
  linear_color_scheme: schemeYlOrBr
  metric: count
  normalize_across: heatmap
  row_limit: 10000
  show_legend: true
  show_perc: true
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: heatmap
  xscale_interval: null
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  yscale_interval: null
cache_timeout: null
uuid: cd111331-d286-4258-9020-c7949a109ed2
version: 1.0.0
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
