slice_name: Vaccine Candidates per Country & Stage
description: null
certified_by: null
certification_details: null
viz_type: heatmap
params:
  adhoc_filters: []
  all_columns_x: clinical_stage
  all_columns_y: country_name
  bottom_margin: auto
  canvas_image_rendering: pixelated
  datasource: 14__table
  left_margin: auto
  linear_color_scheme: schemeYlOrBr
  metric: count
  normalize_across: heatmap
  row_limit: 10000
  show_legend: true
  show_perc: true
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: heatmap
  xscale_interval: null
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  yscale_interval: null
  annotation_layers: []
query_context: '{"datasource":{"id":20,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count"],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"adhoc_filters":[],"all_columns_x":"clinical_stage","all_columns_y":"country_name","annotation_layers":[],"bottom_margin":"auto","canvas_image_rendering":"pixelated","datasource":"20__table","left_margin":"auto","linear_color_scheme":"schemeYlOrBr","metric":"count","normalize_across":"heatmap","row_limit":10000,"show_legend":true,"show_perc":true,"slice_id":76,"sort_x_axis":"alpha_asc","sort_y_axis":"alpha_asc","time_range":"No
  filter","time_range_endpoints":["inclusive","exclusive"],"url_params":{},"viz_type":"heatmap","xscale_interval":null,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","yscale_interval":null,"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 269a8a87-f568-481d-a532-248d8846bd46
version: 1.0.0
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
