slice_name: Vaccine Candidates by Country
description: null
certified_by: null
certification_details: null
viz_type: world_map
params:
  datasource: 20__table
  viz_type: world_map
  entity: country_name
  country_fieldtype: name
  metric: count
  adhoc_filters: []
  row_limit: 10000
  show_bubbles: true
  secondary_metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: country_name
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 728
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: TEXT
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT(country_name)
    optionName: metric_owprszygfi_japmrl1q37
  max_bubble_size: '25'
  color_picker:
    r: 33
    g: 159
    b: 236
    a: 1
  color_by: country
  linear_color_scheme: superset_seq_1
  color_scheme: preset-v1
  y_axis_format: SMART_NUMBER
  extra_form_data: {}
  dashboards:
  - 8
query_context: '{"datasource":{"id":20,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":["count",{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"country_name","description":null,"expression":null,"filterable":true,"groupby":true,"id":728,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"TEXT","type_generic":1,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(country_name)","optionName":"metric_owprszygfi_japmrl1q37"}],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"20__table","viz_type":"world_map","entity":"country_name","country_fieldtype":"name","metric":"count","adhoc_filters":[],"row_limit":10000,"show_bubbles":true,"secondary_metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"country_name","description":null,"expression":null,"filterable":true,"groupby":true,"id":728,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"TEXT","type_generic":1,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT(country_name)","optionName":"metric_owprszygfi_japmrl1q37"},"max_bubble_size":"25","color_picker":{"r":33,"g":159,"b":236,"a":1},"color_by":"country","linear_color_scheme":"superset_seq_1","color_scheme":"preset-v1","y_axis_format":"SMART_NUMBER","extra_form_data":{},"dashboards":[8],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a5275e43-042b-446a-8ad1-ed4ab2c5d279
version: 1.0.0
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
