slice_name: Vaccine Candidates per Phase
viz_type: pie
params:
  adhoc_filters: []
  color_scheme: supersetColors
  datasource: 69__table
  donut: true
  groupby:
  - clinical_stage
  innerRadius: 44
  label_line: true
  labels_outside: true
  metric: count
  number_format: SMART_NUMBER
  outerRadius: 61
  label_type: key
  queryFields:
    groupby: groupby
    metric: metrics
  row_limit: 10000
  show_labels: true
  show_legend: false
  slice_id: 3957
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: pie
cache_timeout: null
uuid: 30b73c65-85e7-455f-bb24-801bb0cdc670
version: 1.0.0
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
