slice_name: Vaccine Candidates per Approach & Stage
description: null
certified_by: null
certification_details: null
viz_type: heatmap
params:
  adhoc_filters: []
  all_columns_x: clinical_stage
  all_columns_y: product_category
  bottom_margin: auto
  canvas_image_rendering: pixelated
  datasource: 69__table
  left_margin: auto
  linear_color_scheme: schemeYlOrBr
  metric: count
  normalize_across: heatmap
  queryFields:
    metric: metrics
  row_limit: 10000
  show_legend: false
  show_perc: true
  show_values: true
  slice_id: 3962
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  time_range: No filter
  time_range_endpoints:
  - inclusive
  - exclusive
  url_params: {}
  viz_type: heatmap
  xscale_interval: null
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  yscale_interval: null
  annotation_layers: []
cache_timeout: null
uuid: 04042714-db44-4798-8557-cc0bf251a15d
version: 1.0.0
dataset_uuid: 974b7a1c-22ea-49cb-9214-97b7dbd511e0
