slice_name: Weekly Messages
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  datasource: 8__table
  viz_type: big_number
  slice_id: 114
  x_axis: ts
  time_grain_sqla: P1W
  metric: count
  adhoc_filters:
  - clause: WHERE
    subject: ts
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  compare_lag: 1
  compare_suffix: WoW
  show_trend_line: true
  start_y_axis_at_zero: true
  time_range_fixed: false
  color_picker:
    r: 88
    g: 78
    b: 160
    a: 1
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  rolling_type: None
  extra_form_data: {}
  dashboards:
  - 12
cache_timeout: null
uuid: fa7e8998-3852-459b-9a10-550293926455
version: 1.0.0
dataset_uuid: e032c69e-716e-d700-eff7-07800d0f9989
