slice_name: World's Population
description: null
certified_by: null
certification_details: null
viz_type: big_number
params:
  compare_lag: '10'
  compare_suffix: over 10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby: []
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 5000
  show_bubbles: true
  since: '2000'
  time_range: '2014-01-01 : 2014-01-02'
  time_range_endpoints:
  - inclusive
  - exclusive
  until: '2014-01-02'
  viz_type: big_number
cache_timeout: null
uuid: 6e9c71ae-faae-4aff-8f08-e0c29e692e8c
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
